In [1]:
import numpy as np#range of array
ar1=np.arange(13)
ar1
len(ar1)

13

In [2]:
r=ar1.reshape(1,13)#to convert to multidimensional array
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [3]:
#identity matrix can be created using two functions
#eye() -> used to define both user defined rows and columns
#identity() -> used to define number of rows and columns
#syntax: np.identity(5) -> 5 is 5 rows and 5 columns
         #np.eye(3,4) -> 3 rows and 4 columns
np.eye(3,4)#identity matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [7]:
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
ar1[1:4]#slicing


array([1, 2, 3])

In [25]:
#to perform multidimensional slicing
ar1=np.arange(25).reshape(5,5)#ar2[rows,columns,step]
ar1
#ar2[row_start:row_end,col_start:col_end,step]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ar1[-4:-2,-4:-2]#negative indexing

array([[ 6,  7],
       [11, 12]])

In [27]:
ar1[1:4,1:4]#positive indexing

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [33]:
ar3#=np.arange(50).reshape(5,10)
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:
np.sum(ar3)


1225

In [35]:
np.sum(ar3,axis=0)#to add based on columns wise axis=0

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [36]:
np.sum(ar3,axis=1)#to add based on row wise axis=1

array([ 45, 145, 245, 345, 445])

In [37]:
#mean ->average
#median ->middle value
#mode -> max no of repeated elements
#variance -> median/total no of elements
#std -> square root of variance
np.mean(ar3)

24.5

In [38]:
np.median(ar3)

24.5

In [40]:
np.var(ar3)

208.25

In [41]:
np.std(ar3)

14.430869689661812

In [43]:
#linspace
#it is used to print the evenly seperated pointed between two range of values
#it is in floating point only
#linspace(start,end,no of parts)
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [44]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [192]:
#random module
#to generate random number between the range
#np.random.randint(start,end)
#np.random.randint(40)
np.random.randint(29,42,2)

array([33, 36])

In [194]:
#rand() ->
#to get the randomly generated values from o to 1,based on uniform distribution
np.random.rand(5,4)

array([[0.31452269, 0.4707365 , 0.18908082, 0.10435268],
       [0.15870272, 0.22235274, 0.11425339, 0.98376829],
       [0.45365715, 0.35748775, 0.44612494, 0.13270913],
       [0.52818985, 0.38173648, 0.13510179, 0.59767907],
       [0.4830032 , 0.38700899, 0.66566046, 0.46105753]])

In [196]:
ar3.min()

0

In [197]:
ar3.max()

49

In [202]:
#to find the index of minimum value and max value
a=[11,22,33,44,55]
n=np.array(a)
print(n.argmin())
print(n.argmax())

0
4


In [209]:
cot=np.cos(a)/np.sin(a)#to find sin,cos,tan,cot etc
cot

array([-4.42574133e-03,  1.12973210e+02, -1.32779175e-02,  5.64821794e+01,
       -2.21321748e-02])

In [213]:
#task1
np2=np.array([1,2,3,8])
np3=np.array([4,5,6,1])
#(1*4)+(2*5)+(3*6)=4+10+18=32 output
r=np.dot(np2,np3)#or np2*np3
r

40

In [220]:
np2=np.array([1,2,3,8,3,5,9])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for i in range(diff):
    np3=np.append(np3,1)
sum(np2*np3)

57

In [225]:
np1=np.array([1,34,56,np.nan,np.nan])
#to print nan values
print(np1[np.isnan(np1)])
print(np1[~np.isnan(np1)])

[nan nan]
[ 1. 34. 56.]


In [227]:
pip list

Package                       Version
----------------------------- ---------------
aiobotocore                   2.5.0
aiofiles                      22.1.0
aiohttp                       3.8.5
aioitertools                  0.7.1
aiosignal                     1.2.0
aiosqlite                     0.18.0
alabaster                     0.7.12
anaconda-anon-usage           0.4.2
anaconda-catalogs             0.2.0
anaconda-client               1.12.1
anaconda-cloud-auth           0.1.3
anaconda-navigator            2.5.0
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
async-timeout                 4.0.2
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8

In [ ]:
#PANDAS
#pandas is defined as an open-source library that provides high performance data manipulation in python
#data analysis requires lot of processing such as restructing ,cleaning,merging,manipulating,etc--
#we prefer pandas to perform above functionalities coz it is fast ,simple than other tools.
#Pandas is built on numpy,numpy is required for operating pandas.


#PANDAS SERIES
#pandas series is a data structure with one dimensional labelled array
#It is a primary building block of DataFrame,making its rows and columns

#syntax--> pandas.series(data=None,dtype=None,name=None,copy=True or False)

In [232]:
import pandas as pd
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100,'b':200,'c':300}
print(pd.Series(my_data))
print(type(pd.Series(my_data)))


0    10
1    20
2    30
dtype: int64
<class 'pandas.core.series.Series'>


In [233]:
pd.Series(data=my_data,index=labels)#or pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [235]:
pd.Series(data=[print(),sum,len])

0                       None
1    <built-in function sum>
2    <built-in function len>
dtype: object

In [239]:
class profile:
    def display(self):
        print("hello world")
p=profile()
p.display()
def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner
@decor
def greet():
    return "good morning"
print(greet())

hello world
GOOD MORNING


In [244]:
series=pd.Series([1,2,3,4,5],['USA','CANADA','INDIA','UK','EGYPT'])
print(series)
print(series[::-1])

USA       1
CANADA    2
INDIA     3
UK        4
EGYPT     5
dtype: int64
EGYPT     5
UK        4
INDIA     3
CANADA    2
USA       1
dtype: int64


In [247]:
print(series['INDIA'])# value using key
print(series[1])# value using indexing
print(series[0:3])#slicing

3
2
USA       1
CANADA    2
INDIA     3
dtype: int64


In [255]:
#to create a new data in series
series['china']=9
series

USA       1
CANADA    2
INDIA     3
UK        4
EGYPT     5
china     9
dtype: int64

In [256]:
#Data Frame
#p.DataFrame(datas,row_label,col_label)
df=pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0  1.425431  0.062852  0.349976 -0.194785
1 -0.513502  1.219584  0.722770 -0.738441
2 -0.243897  0.094204 -0.552899 -1.140478
3 -0.301490 -0.322363  0.348794  1.421984
4 -0.426665  1.321059  0.004493 -1.662584

In [262]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])



In [259]:
#to convert dictionary to data frame
d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}
d1=pd.DataFrame(data=d)
d1

col1  col2  col3
0     1     3     5
1     2     4     6

In [260]:
df=pd.DataFrame(d,["row1","row2"])
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [265]:
print(df.index)#get all the row names
print(df.columns)#get all the column names

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
Index(['W', 'X', 'Y', 'Z'], dtype='object')


In [263]:
df

W         X         Y         Z
A  0.201426 -2.036125  0.818853 -1.164185
B -0.609353 -0.427630 -0.060054  1.841181
C -0.515537  0.156210  0.388101 -1.404430
D  1.690428  0.685394  0.006702 -0.421292
E  1.894825 -0.569500  2.345447 -1.338564

In [264]:
df.T#transpose

A         B         C         D         E
W  0.201426 -0.609353 -0.515537  1.690428  1.894825
X -2.036125 -0.427630  0.156210  0.685394 -0.569500
Y  0.818853 -0.060054  0.388101  0.006702  2.345447
Z -1.164185  1.841181 -1.404430 -0.421292 -1.338564

In [266]:
df.dtypes#data type of each column

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [267]:
df.info()#to get information about data frame

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [268]:
df.axes

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['W', 'X', 'Y', 'Z'], dtype='object')]

In [269]:
df.values

array([[ 0.2014257 , -2.03612527,  0.81885318, -1.16418473],
       [-0.60935309, -0.42762998, -0.06005427,  1.84118092],
       [-0.51553674,  0.15620969,  0.38810076, -1.40442983],
       [ 1.69042769,  0.68539447,  0.00670153, -0.42129206],
       [ 1.89482496, -0.56949961,  2.34544652, -1.3385638 ]])

In [270]:
df.ndim#dimension

2

In [271]:
df.size

20

In [272]:
#to access specific column of dataframe
df['W']

A    0.201426
B   -0.609353
C   -0.515537
D    1.690428
E    1.894825
Name: W, dtype: float64

In [273]:
type(df['W'])

pandas.core.series.Series

In [274]:
#to access multiple columns
df[['W','X','Y']]

W         X         Y
A  0.201426 -2.036125  0.818853
B -0.609353 -0.427630 -0.060054
C -0.515537  0.156210  0.388101
D  1.690428  0.685394  0.006702
E  1.894825 -0.569500  2.345447

In [288]:
#to create a new column
df['new']=df['W']+df['Y']
df

W         X         Y         Z       new
A  0.201426 -2.036125  0.818853 -1.164185  1.020279
B -0.609353 -0.427630 -0.060054  1.841181 -0.669407
C -0.515537  0.156210  0.388101 -1.404430 -0.127436
D  1.690428  0.685394  0.006702 -0.421292  1.697129
E  1.894825 -0.569500  2.345447 -1.338564  4.240271

In [291]:
df.drop('new',axis=1,inplace=True)

In [292]:
df

W         X         Y         Z
A  0.201426 -2.036125  0.818853 -1.164185
B -0.609353 -0.427630 -0.060054  1.841181
C -0.515537  0.156210  0.388101 -1.404430
D  1.690428  0.685394  0.006702 -0.421292
E  1.894825 -0.569500  2.345447 -1.338564