In [1]:
import numpy as np
n=[1,2,3,4]
ar1=np.array(n)#creating array
ar1

array([1, 2, 3, 4])

In [4]:
#conversion of array to list
ar={'sai':1,'shannu':2}
l=np.array(ar)
l.tolist()
l

array({'sai': 1, 'shannu': 2}, dtype=object)

In [5]:
#inserting elements to list at particular position
n=[1,2,3,4]
m=np.insert(n,2,(10,20))
m

array([ 1,  2, 10, 20,  3,  4])

In [11]:
#delete
n=[1,2,3,4,5]
new=np.delete(n,[1])
new

array([1, 3, 4, 5])

In [13]:
#to delete multiple values
nr=np.setdiff1d(n,[0,2,4])
nr

array([1, 3, 5])

In [15]:
#to delete multiple values based on index
a=np.delete(n,[2,3])
a

array([1, 2, 5])

In [16]:
#to print elements less than 30
l1=[1,33,-2,55/77,66,77,88,99]
a=np.array(l1)
a[a<30]


array([ 1.        , -2.        ,  0.71428571])

In [18]:
#to replace the value
n[n==2]=20
n

[20, 2, 3, 4, 5]

In [20]:
#to create array full of zeros and ones
print(np.zeros(7))#zeros
print(np.ones(7))#ones

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]


In [21]:
#to create two dimensional array
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
#complex
np.ones([2,5],dtype='complex')

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [23]:
np.ones([7,3],dtype='float')

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
#class
class c1:
    name="shannu"
    age=19
o=c1()
print(o.name)

shannu
